# 项目链接
projects_url: https://github.com/wybbb1

# 导航菜单
nav:
  home: /
  articles: /archives/
  categories: /categories/

# 社交链接
social_links:
  - icon: github
    link: https://github.com/wybbb1
  - icon: mail
    link: mailto:rainbotwyb@163.com

colorscheme: light

# 自定义CSS注入（用于覆盖字体等样式）
custom_css: /css/custom.css

post:
  show_updated: true